services:
  database:
    image: postgres:16-alpine
    ports:
      - "5434:5432"
    volumes:
      - ./database/init.sh:/docker-entrypoint-initdb.d/init.sh
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  go-multitenancy:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    links:
      - database:database
    ports:
      - "8080:8080"
    environment:
      - TENANTS=tenant1,tenant2
      - TENANT1_DB_HOST=database
      - TENANT1_DB_PORT=5432
      - TENANT1_DB_NAME=tenant1db
      - TENANT1_DB_USERNAME=postgres
      - TENANT1_DB_PASSWORD=postgres
      - TENANT2_DB_HOST=database
      - TENANT2_DB_PORT=5432
      - TENANT2_DB_NAME=tenant2db
      - TENANT2_DB_USERNAME=postgres
      - TENANT2_DB_PASSWORD=postgres
      - MIGRATION_SOURCE_URL=/app/migrations